### ISSUE TITLE
run/compile instructions

### ISSUE THREAD

**Issue by qubodup** [tzorca/unnamed-platformer#46]
Hello,

I just used github search to find some new open source games and found this project, which I'd love to try playing.

Unfortunately I'm not much of a developer and can't figure out how to compile it.

Instructions in the readme would be welcome!

**Comment by ehgoodenough** [comment]
Hi! It's great to hear your interest! @tzorca created a binary of the game, which you can access at the [releases page](https://github.com/tzorca/unnamed-platformer/releases), but I'm not sure how up to date they are. Hope that helps!

**Comment by qubodup** [comment]
Thanks!

I get into the menu but not into the game. I run with java -jar FILENAME.jar

I can navigate back with Z and to make buttons visible in the level select I need to press X.

Video: http://youtu.be/Zzu8ZAR-rKg
Output: http://codepad.org/OYBznq8P

My system:

    $ java -version
    java version "1.7.0_75"
    OpenJDK Runtime Environment (IcedTea 2.5.4) (Arch Linux build 7.u75_2.5.4-1-x86_64)
    OpenJDK 64-Bit Server VM (build 24.75-b04, mixed mode)

Arch Linux
Awesome WM (a tiled window manager, tends to have issues with Java apps)
Might also be the fault of the open source ATI graphics driver.

Runs fine on Windows 8.1 though.Curse those gravity-defying lava tiles! :D

**Comment by tzorca** [comment]
Thanks for trying my game! Really appreciate the feedback.

I plan to add build instructions later today, and also make a new release with all the things I've been working on since last release. I will also try updating the LWJGL library, as I have read that may solve some of the Linux display issues.

In the meantime, you might be able to get it to work on Linux by changing DEFAULTS_TO_FULLSCREEN to true in settings.ini, or by trying a different JVM.

Control choices are not very intuitive right now, so at some point I definitely need to update them to be more user-friendly.

Again, thanks! I would love to hear more feedback if you have any.
